### ISSUE TITLE
Excuse me,Could you give any instruction about how to run the code? 

### ISSUE THREAD

**Issue by lz321cc321** [pparmesh/Constrained_ILQR#1]
hi!Prateek Parmeshwar
I only get this follow result, but can't get this overtake result.
Can you tell me how can I get this overtake result?

![屏幕截图 2022-01-10 204316](https://user-images.githubusercontent.com/88258935/148769664-2ca1567a-54b9-45ba-b96d-1f8fe8995858.png)
![屏幕截图 2022-01-10 204332](https://user-images.githubusercontent.com/88258935/148769681-54ab8444-409b-4f83-8145-c771bff3aa0c.png)
Best regards:
han zhen

**Comment by pparmesh** [comment]
Hi Han,
Try playing around with the costs for deviation from reference trajectory and deviation from desired speed. I don't recall the exact values for those costs unfortunately.
