### ISSUE TITLE
hi,i want to know how to run this code

### ISSUE THREAD

**Issue by gaoyuhui-pp** [pparmesh/Constrained_ILQR#2]
i want to know how to run this code,thank you!

**Comment by cthlinmeng** [comment]
there is a main function in the python_simulator.py.

**Comment by cthlinmeng** [comment]
> i want to know how to run this code,thank you!
there is a main function in python_simulator.py

**Comment by ggggo0** [comment]
你好，请问λ µ的更新公式具体在那一节体现呢？代码里只有lamb的更新
